//A FUNÇÃO ABAIXO RECEBE UMA PALAVRA COMO PARAMETRO E INVERTE A ORDEM DELA
//1º CRIO UMA FUNÇÃO COM NOME EXERCICIO E PARAMETRO CHAMADO PALAVRA
//2º CRIO UM LOOP QUE O PRIMEIRO PARAMETRO IRÁ RECEBER O TOTAL DE CARACTERES DA PALAVRA
//E ENQUANTO O VALOR DE i FOR MAIOR QUE ZERO ELE VAI DANDO VOLTAS E EXECUTANDO O CODIGO
// E VAI DECREMENTANDO O VALOR DE i E RETORNANDO UM NUMERO QUE SERÁ USADO COMO INDICE PARA RETORNAR A PALAVRA 
function exercicio (palavra){
    for(let i=palavra.length; i>=0; i--){
        console.log(palavra[i]);
    }

}
exercicio("Charlon");